### ISSUE TITLE
README breakage, at link and command

### ISSUE THREAD

**Issue by bradyt** [purcell/reformatter.el#15]
This link is apparently broken:

> * [Here](https://github.com/manuel-uberti/.emacs.d/commit/464ef5744dc22eb6cdea73e524cd615872ad24c4) is a user defining a reformatter in his own configuration

That is, https://github.com/manuel-uberti/.emacs.d/commit/464ef5744dc22eb6cdea73e524cd615872ad24c4.

I did not see a reformatter command.

> See the command `reformatter`.

**Comment by purcell** [comment]
Thanks for reporting this - fixed now.

**Comment by manuel-uberti** [comment]
Sorry about this, my Emacs configuration changes often. :)

**Comment by purcell** [comment]
No worries @manuel-uberti :-)
