### ISSUE TITLE
Support formatters which don't accept input from stdin

### ISSUE THREAD

**Issue by clemera** [purcell/reformatter.el#18]
Some formatters like `isort` need a file as input and change the file in place . An additional argument like `:file t` could result in creating a temp file and pass that to `:program` and use the changed temp file as new buffer content.

**Comment by chmouel** [comment]
Same goes for python's `black` https://github.com/psf/black

**Comment by purcell** [comment]
> Same goes for python's `black` https://github.com/psf/black

No, that can definitely work on `stdin` and `stdout`. Look at the existing `blacken-mode` code: https://github.com/pythonic-emacs/blacken/blob/5f30f17b048af1fe73ba710781650e3490a7be49/blacken.el#L82-L104

**Comment by purcell** [comment]
> An additional argument like `:file t` could result in creating a temp file and pass that to `:program` and use the changed temp file as new buffer content.

That sounds quite nice. Will try to get get to something like that soon.

**Comment by clemera** [comment]
This looks great! Thank you!
