### ISSUE TITLE
Spacemacs example

### ISSUE THREAD

**Issue by backwardspy** [purcell/reformatter.el#6]
Hi! Thanks for reformatter.el, it's super cool.

I made a simple Spacemacs layer that uses reformatter.el and [black](https://github.com/ambv/black) to format python code.

I don't know if you are interested in adding any more examples to the readme, but if you want to you are welcome to link to spaceblacken. No worries if not!

The project can be found here: https://github.com/backwardspy/spaceblacken

**Comment by purcell** [comment]
Neat! Thanks for the example, and I'm happy to see it was useful. I'm not going to add more examples just now, but I'll bear this in mind if I do later. :-)
