### ISSUE TITLE
generic configuration and ‘dwim’ helpers

### ISSUE THREAD

**Issue by wbolster** [purcell/reformatter.el#9]
this package is, by design, conceptually different from `format-all`. however, it is convenient to have have a single command as an entry-point to format a buffer (or region). this also makes keybindings easier.

a minimal ‘dwim’ (do what i mean) command would only need the name of the reformatter (as defined by `reformatter-define`. a buffer-local variable pointing to a ‘reformatter command family’ is enough to make ‘dwim’ commands that delegate to the real reformatter commands.

i'll post my implementation in a separate comment. i think this may be useful for others as well, and i'm posting this here to see whether it would make sense to add this to `reformatter.el` proper. (obviously i think it does. it's what makes this package really useful for me.)

**Comment by wbolster** [comment]
here's a `reformatter-dwim.el` with add-ons for `reformatter.el`:

- `reformatter-dwim-region`
- `reformatter-dwim-buffer`
- `reformatter-dwim-on-save-mode`
- `reformatter-dwim-evil`  (see #7)

these commands can be used in keybindings.

```elisp
;;; reformatter-dwim.el --- dwim reformatter helpers -*- lexical-binding: t; -*-

(require 'subr-x)
(require 'evil)
(require 'reformatter)

(defgroup reformatter-dwim nil
  "reformatter dwim helpers"
  :group 'reformatter
  :prefix "reformatter-dwim-")

(defcustom reformatter-dwim-reformatter nil
  "The currently active reformatter.

This should be a symbol, which is used to find the corresponding
reformatting commands. For example, setting this variable to 'foo
will result in the commands 'foo-region and 'foo-buffer be used for
reformatting.

Typically, a major mode hook should set this buffer-local variable."
  :group 'reformatter-dwim
  :type 'symbol)

(make-variable-buffer-local 'reformatter-dwim-reformatter)

;;;###autoload
(defun reformatter-dwim-region (beg end &optional display-errors)
  "Reformat the region from BEG to END."
  (interactive "rp")
  (let ((fun (reformatter-dwim--command 'region)))
    (funcall-interactively fun beg end display-errors)))

;;;###autoload
(defun reformatter-dwim-buffer (&optional display-errors)
  "Reformat the current buffer."
  (interactive "p")
  (let ((fun (reformatter-dwim--command 'buffer)))
    (funcall-interactively fun display-errors)))

;;;###autoload
(defun reformatter-dwim-on-save-mode (&optional arg)
  "Toggle automatic reformatting when saving."
  (interactive "p")
  (let ((fun (reformatter-dwim--command 'on-save-mode)))
    (funcall-interactively fun arg)))

;;;###autoload
(evil-define-operator reformatter-dwim-evil (beg end _type)
  "Evil operator to reformat a region."
  :type line
  :repeat nil
  (interactive "<R>")
  (reformatter-dwim-region beg end))

(defun reformatter-dwim--command (suffix)
  "Get the currently configured reformatter function.

The symbol SUFFIX is used to construct the complete name."
  (unless reformatter-dwim-reformatter
    (user-error "No reformatter configured for current buffer (reformatter-dwim-reformatter not set)"))
  (if-let* ((name (format "%s-%s" (symbol-name reformatter-dwim-reformatter) (symbol-name suffix)))
            (fun (intern name))
            (fun-is-a-function (functionp fun)))
      fun
    (user-error
     "Reformatter %s not found. Is the package defining the reformatter loaded?"
     reformatter-dwim-reformatter)))

(provide 'reformatter-dwim)
;;; reformatter-dwim.el ends here
```

**Comment by purcell** [comment]
Thanks - interesting discussion. This is a little antithetical to the `reformatter` approach, so I'm not particularly keen to incorporate the machinery as above, sorry: it undoes some of the things that `reformatter` aimed to address, for example your code assumes that there will only be one reformatter per buffer, which is suprisingly often not the case!

So then you'd have to get into configuring multiple reformatters, calling them in sequence etc., and then you end up with something resembling `format-all`. :-) 

I'd suggest that if the `format-all` model is appealing to you, then a good way to proceed might be to make `format-all` able to handle any `reformatter.el`-based reformatters you're using.

**Comment by wbolster** [comment]
heh, actually i'm more fond of the `reformatter` approach than the `format-all` approach. having small dedicated packages using `reformatter` under the hood than the ‘do everything’ approach taking by `format-all`.

but in my opinion that doesn't mean i can't have nice things :) making the simple case simple (while making the complex cases possible) is exactly what my `-dwim` family of commands tries to achieve. it's very convenient to have a keybinding that usually does ‘the right thing’ and if that's not possible (e.g. no reformatter for the current major mode) it will show a useful error message.

also, about single buffer would use multiple formatters: the only case i can think of is markdown with embedded code snippets (and similar things). this is where `reformatter` would be used in its ‘pure form’, e.g. by invoking `xyz-region` on the embedded snippet.

if you really can't be convinced that some ‘dwim’ helpers for `reformatter` give it a (imho much needed) ergonomic advantage for the common use case (single reformatter per major mode), what course of action do you suggest?

i would be happy to publish `reformatter-dwim` as a separate melpa package, but i'd like to have your ‘blessing’ and make it a ‘friendly’ add-on package. another name may be desirable. ideas/thoughts welcome!

(btw can you reopen this ticket while discussing? it makes it much easier to find on github, e.g. via the [issue overview](https://github.com/issues))
